# Generated by Django 4.0.1 on 2022-01-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Patronymic')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('birthday_place', models.CharField(max_length=128, verbose_name='Birthday place')),
                ('sex', models.CharField(choices=[(None, 'Unknown'), ('ML', 'Male'), ('FM', 'Female'), ('X', 'X')], default='X', max_length=32, verbose_name='Sex')),
                ('passport_series', models.CharField(max_length=8, verbose_name='Passport series')),
                ('passport_number', models.CharField(max_length=64, unique=True, verbose_name='Passport number')),
                ('passport_issued_by', models.CharField(max_length=128, verbose_name='Passport issuer')),
                ('passport_issued_at', models.DateField(verbose_name='Passport issue date')),
                ('id_number', models.CharField(max_length=128, unique=True, verbose_name='Identification number')),
                ('city', models.CharField(choices=[(None, 'Unknown'), ('MINSK', 'Minsk'), ('MOGILEV', 'Mogilev'), ('VITEBSK', 'Vitebsk'), ('GOMEL', 'Gomel'), ('BREST', 'Brest'), ('MOSCOW', 'Moscow'), ('WARSAWA', 'Warsawa'), ('KYIV', 'Kyiv'), ('VILNIUS', 'Vilnius')], max_length=128, verbose_name='City')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('home_number', models.CharField(max_length=32, null=True, verbose_name='Home number')),
                ('phone_number', models.CharField(max_length=32, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('job_place', models.CharField(max_length=128, null=True, verbose_name='Job place')),
                ('job_position', models.CharField(max_length=256, null=True, verbose_name='Job position')),
                ('register_city', models.CharField(choices=[(None, 'Unknown'), ('MINSK', 'Minsk'), ('MOGILEV', 'Mogilev'), ('VITEBSK', 'Vitebsk'), ('GOMEL', 'Gomel'), ('BREST', 'Brest'), ('MOSCOW', 'Moscow'), ('WARSAWA', 'Warsawa'), ('KYIV', 'Kyiv'), ('VILNIUS', 'Vilnius')], max_length=128, verbose_name='Registration city')),
                ('register_address', models.CharField(max_length=256, verbose_name='Registration address')),
                ('family_status', models.CharField(choices=[(None, 'Unknown'), ('MR', 'Married'), ('SG', 'Singleness'), ('DV', 'Divorced'), ('CL', 'Common-law')], max_length=32, verbose_name='Sex')),
                ('citizen', models.CharField(choices=[(None, 'Unknown'), ('BLR', 'Belarus'), ('RUS', 'Russian'), ('UKR', 'Ukraine'), ('PLN', 'Poland'), ('LTU', 'Lithuania')], max_length=128, verbose_name='Citizen')),
                ('disability', models.IntegerField(choices=[(None, 'Unknown'), (0, 'Group 0'), (1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3')], default=0, verbose_name='Disability group')),
                ('pensioner', models.BooleanField(default=False, verbose_name='Pensioner')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Monthly salary')),
                ('army', models.BooleanField(default=True, verbose_name='Liable for military service')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name'],
            },
        ),
    ]
