# Generated by Django 4.0.1 on 2022-01-29 20:08

from django.db import migrations, models

import client_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='army',
            field=models.BooleanField(verbose_name='Liable for military service'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(validators=[client_app.validators.validate_date], verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizen',
            field=models.CharField(choices=[(None, 'Unknown'), ('Belarus', 'Belarus'), ('Russian', 'Russian'), ('Ukraine', 'Ukraine'), ('Poland', 'Poland'), ('Lithuania', 'Lithuania')], max_length=128, verbose_name='Citizen'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[(None, 'Unknown'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'), ('Gomel', 'Gomel'), ('Brest', 'Brest'), ('Moscow', 'Moscow'), ('Warsawa', 'Warsawa'), ('Kyiv', 'Kyiv'), ('Vilnius', 'Vilnius')], max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='disability',
            field=models.IntegerField(choices=[(None, 'Unknown'), (0, 'Group 0'), (1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3')], verbose_name='Disability group'),
        ),
        migrations.AlterField(
            model_name='client',
            name='family_status',
            field=models.CharField(choices=[(None, 'Unknown'), ('Married', 'Married'), ('Singleness', 'Singleness'), ('Divorced', 'Divorced'), ('Common-law', 'Common-law')], max_length=32, verbose_name='Family status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_issued_at',
            field=models.DateField(validators=[client_app.validators.validate_date], verbose_name='Passport issue date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pensioner',
            field=models.BooleanField(verbose_name='Pensioner'),
        ),
        migrations.AlterField(
            model_name='client',
            name='register_city',
            field=models.CharField(choices=[(None, 'Unknown'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'), ('Gomel', 'Gomel'), ('Brest', 'Brest'), ('Moscow', 'Moscow'), ('Warsawa', 'Warsawa'), ('Kyiv', 'Kyiv'), ('Vilnius', 'Vilnius')], max_length=128, verbose_name='Registration city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[(None, 'Unknown'), ('Male', 'Male'), ('Female', 'Female'), ('X', 'X')], max_length=32, verbose_name='Sex'),
        ),
    ]
