# Generated by Django 4.0.1 on 2022-01-31 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_alter_client_army_alter_client_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday_place',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Incorrect birthday place', regex='^[a-zA-Zа-яА-Я]+[a-zA-Zа-яА-Я-]+[a-zA-Zа-яА-Я]+$')], verbose_name='Birthday place'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Incorrect first name', regex='^[a-zA-Zа-яА-Я]+[a-zA-Zа-яА-Я-]+[a-zA-Zа-яА-Я]+$')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_number',
            field=models.CharField(max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Incorrect home number', regex='^[0-9]{7}$')], verbose_name='Home number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect ID number', regex='^[0-9]{7}[аАвВсСкКеЕмМнН][0-9]{3}(PB|BA|BI)[0-9]$')], verbose_name='Identification number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Incorrect last name', regex='^[a-zA-Zа-яА-Я]+[a-zA-Zа-яА-Я-]+[a-zA-Zа-яА-Я]+$')], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect passport number', regex='^[0-9]{7}$')], verbose_name='Passport number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_series',
            field=models.CharField(choices=[('AB', 'AB'), ('BM', 'BM'), ('HB', 'HB'), ('KH', 'KH'), ('MP', 'MP'), ('MC', 'MC'), ('KB', 'KB'), ('PP', 'PP'), ('SP', 'SP'), ('DP', 'DP')], max_length=8, verbose_name='Passport series'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Incorrect patronymic', regex='^[a-zA-Zа-яА-Я]+[a-zA-Zа-яА-Я-]+[a-zA-Zа-яА-Я]+$')], verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Incorrect phone number', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')], verbose_name='Phone number'),
        ),
    ]
