# Generated by Django 4.0.1 on 2022-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_client_birthday_place_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True, verbose_name='Monthly salary'),
        ),
    ]
