# Generated by Django 4.0.1 on 2022-02-10 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Incorrect passport number', regex='^[0-9]{7}$')], verbose_name='Passport number'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('passport_series', 'passport_number')},
        ),
    ]
