# Generated by Django 4.0.1 on 2022-02-05 14:39

import base_app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0001_initial'),
        ('deposit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositcontract',
            name='deposit_bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts_deposit', to='bank_account_app.bankaccount', verbose_name='Deposit bank account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositcontract',
            name='main_bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts_main', to='bank_account_app.bankaccount', verbose_name='Main bank account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositcontract',
            name='ends_at',
            field=models.DateField(validators=[base_app.validators.validate_date_on_future], verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='depositcontract',
            name='starts_at',
            field=models.DateField(validators=[base_app.validators.validate_date_on_future], verbose_name='Start date'),
        ),
    ]
