# Generated by Django 4.0.1 on 2022-02-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_app', '0003_alter_bankaccount_client'),
        ('deposit_app', '0003_alter_depositcontract_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositcontract',
            name='special_bank_account',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.RESTRICT, related_name='contracts_special', to='bank_account_app.bankaccount', verbose_name='Special bank account'),
            preserve_default=False,
        ),
    ]
