# Generated by Django 4.0.1 on 2022-02-09 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_app', '0005_depositcontract_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittype',
            name='max_downpayment',
            field=models.DecimalField(decimal_places=2, max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum downpayment'),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='min_downpayment',
            field=models.DecimalField(decimal_places=2, max_digits=21, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimal downpayment'),
        ),
    ]
