version: "3.9"

services:
  bank:
    restart: always
    build:
      context: ./bank
    ports:
      - "8000:8000"
    command: ["./bank_run.bash"]
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

  client:
    restart: always
    build:
      context: ./bank/webclient
    ports:
      - "4200:4200"
    env_file: ./.env
    depends_on:
      - bank

  db:
    restart: always
    image: postgres
    ports:
      - '5432'
    volumes:
      - ./bank/data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
