# Generated by Django 4.0.1 on 2022-02-20 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account_app', '0003_alter_bankaccount_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Incorrect bank card number', regex='^[0-9]{16}$')], verbose_name='Number')),
                ('pin', models.CharField(max_length=128, verbose_name='PIN')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cards', to='bank_account_app.bankaccount', verbose_name='Bank account')),
            ],
            options={
                'verbose_name': 'Bank card',
                'verbose_name_plural': 'Bank card',
                'ordering': ['number'],
            },
        ),
    ]
