# Generated by Django 4.0.1 on 2022-02-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_client_monthly_salary'),
        ('bank_account_app', '0002_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bank_accounts', to='client_app.client', verbose_name='Client'),
        ),
    ]
